# Generated by Django 5.2.8 on 2025-11-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('prize', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('pdf_rules', models.FileField(blank=True, null=True, upload_to='rules/')),
                ('capacity', models.IntegerField(default=0)),
                ('signed_up', models.IntegerField(default=0)),

            ],
        ),
    ]
