# Generated by Django 6.0 on 2025-12-21 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='registration_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ContestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=255)),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('unique_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_code_used', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='contests.contest')),
            ],
            options={
                'unique_together': {('contest', 'wallet_address')},
            },
        ),
    ]
